"""empty message

Revision ID: 3f98b0d9e1a
Revises: f562e0a41d
Create Date: 2015-01-21 16:23:00.507794

"""

# revision identifiers, used by Alembic.
revision = '3f98b0d9e1a'
down_revision = 'f562e0a41d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name_normalized', sa.String(length=255), nullable=True))
    op.create_unique_constraint('user_tag_constraint', 'tags', ['owner_id', 'type', 'name_normalized'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_tag_constraint', 'tags', type_='unique')
    op.drop_column('tags', 'name_normalized')
    ### end Alembic commands ###
